language: node_js
node_js:
- '0.12'
- '0.11'
- '0.10'
install:
- npm install
- npm install react
script:
- npm run build
deploy:
  - provider: npm
    email: doug@calobrisi.com
    api_key:
      secure: WSNW39+pZV+oDwjPClox24k4ZdimovOuYD584XEc3GSiYPZV6pJO+X4KlMvJKN3JhgOVC+/NXruAhLV1exrSY7tFcUbC6ENt+T3tWzr11vgSuX80ldZ9P7VFWbg3TDNRaH9rxCfJ8bIGJlb5vc1/yMgyYP8H1FzrQYUQsk6IyFQpso57FrFRBs8DZEYKaCOwHhxkcV1VGcGUbZ6TFdkrTkZObHhvHIdLO+tohdnmgMJkoGHvhYkCQSaW3MdQlmkHMQ8YtoO4d/objXZpJdY1fUhlL0nCOwlbmqjtZNQNF2IVGZAuk6QmmYJKCYt0qhsXp4YEYBItn0bipJQRSTS6RlPv14JbKlTZ2WpgP22pOUGUG2Wceifjxhy/bhw40WqVEjwN7/S3VosDA1h3p7jZud48mUMICs5Ol/B1D7rmlOb+f3m0rorxo7lmwJoqDViFQnkF8ZBpokJB0w5F5jeEotqpIcl8LY1uNGAA48lDofGsDYZLOhqva56FHx5ML9CC5Xr2yIdtNKQ4CBYVW+d1cayAYC6eVc9uE6lMPZfWL+1UHfQ+33WXC9Pb4Z3i7jBwMsutwuJ/J9v2pySOjGP3ebwABOtFDbCvi7ywrdB3tD9MFvmlOFk2wDqIJ4hYGm/CDveBKj3GiDIdDiVpExqHLI6nkeY3QBhpsd1oQr7kJXo=
    skip_cleanup: true
    on:
      tags: true
      repo: dougcalobrisi/react-jointjs
  - provider: releases
    api_key:
      secure: n3wWnFRaSXzf6TX4etSOwvUUbpSIVUJf90XY0PTaVmHy2cQd2E1P2SaAmjBONcnyM6S4cBRCiklfSeO0mgFgPjOv48Nee/6LFWCgk9ATyqSFzV+pt8x2bp5lBRLqPuWKJwdLS+xkFFOkRjFT1Cv3oZ2ntXKYn951zQsmxueRXcZtqSAx9BABytYBqKha0cMUK0c0AUZI77W3nAeKcA8Oem+xBhFItcL0/suJ+QMbvS9b2JkcNExnLC32lvtCyWBEgMDJRlu6JkSO8z/dm6Ygibb72wgF+gh2nuQ8szYleDXBrzntNpMtnFngIwmjQjlY9xFmEYrWxNSO0embFHi0OELuvL8wB62u7C0jdVVd1J9XfHUI2orAp9QCricD4cHYQwb7HC+DXCbSkV6Usmzj11BeAy8wUVpQma76OWF2WiPlcgGmVPTMYxchxEK4DkynQc6NaDA3DPkPrY1cBJ7WWjJEqtq7HwlU4zWst0JTb8qHA1gzYKzaA1baDNwn3TW+1odQ5m9DSpaDCiaLp07doTQxfqJRSi9cumgZII+9UDs1+y8bgD3F/ODtyBzuDytlKyQGSXRohKiHmY/eEHLonioqfB++ixAxa3XMi8/LhW3obT2mzf0/3SjFx7qNrIIxc1vmIhmEQrvwodSxM7HYij5lwIp+c7v4e+axZoAdFj8=
    file: dist/react-jointjs.min.js
    skip_cleanup: true
    on:
      tags: true
      repo: dougcalobrisi/react-jointjs
